server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/movie-storage?currentSchema=public
    username: postgres
    password: password
  jpa:
    show-sql: true
  liquibase:
    default-schema: public
    change-log: classpath:changelog/changelog-master.xml

feign:
  page-reader:
    url: http://localhost:8081/page-reader

storage:
  image:
    path: images
    extension: jpg

parser:
  kinopoisk:
    url: https://www.kinopoisk.ru

    premieres:
      url-template: ${parser.kinopoisk.url}/premiere/ru/%d/month/%d/
      premiere-link:
        selector: div.premier_item > div.text > div.textBlock > span.name > a
        attribute: href

    movie:
      title:
        selector: div#headerFilm
      property:
        selector: table.info > tbody > tr
        delimiter: ", "
        unused-lines:
          - "..."
          - "-"
          - "слова"
          - "сборы"
      rating-kinopoisk:
        selector: span.rating_ball
      rating-imdb:
        selector: div.block_2
        delimiter: " "
      poster:
        selector: a.popupBigImage
        attribute: onclick
        unused-lines:
          - "openImgPopup('"
          - "'); return false"